#!/usr/bin/env bash
# apply-standards.sh — Standardize agent docs and DevOps configs across all Shir0o repos.
#
# Usage:
#   ./apply-standards.sh                 # Dry run (default) — shows what would change
#   ./apply-standards.sh --apply         # Apply changes, create branches, commit, open PRs
#   ./apply-standards.sh --apply --repo attd   # Apply to a single repo only
#
# Prerequisites:
#   - gh CLI authenticated (`gh auth status`)
#   - All repos cloned under ~/
#   - This script's sibling `templates/` directory contains the template files

set -euo pipefail

# ─── Configuration ────────────────────────────────────────────────────────────

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TEMPLATES="$SCRIPT_DIR/templates"
HOME_DIR="$HOME"
BRANCH_NAME="chore/standardize-agent-devops"
PR_TITLE="chore: standardize agent docs and DevOps configs"
PR_BODY="Automated standardization of AGENTS.md, CODEOWNERS, dependabot, SECURITY.md, CI, CodeQL, and branch rulesets.

Generated by \`apply-standards.sh\` from the shared template in \`Shir0o/.github\`."

DRY_RUN=true
TARGET_REPO=""

# ─── Parse arguments ─────────────────────────────────────────────────────────

while [[ $# -gt 0 ]]; do
  case "$1" in
    --apply)  DRY_RUN=false; shift ;;
    --repo)   TARGET_REPO="$2"; shift 2 ;;
    *)        echo "Unknown argument: $1"; exit 1 ;;
  esac
done

# ─── Repo registry ───────────────────────────────────────────────────────────
# Format: "local_dir|tier|framework|has_functions|github_repo"
#   tier: 1 or 2
#   framework: flutter, node, godot, python, eleventy
#   has_functions: yes or no (whether it has a functions/ dir with JS/TS)
#   github_repo: Shir0o/<name> on GitHub

REPOS=(
  # ── Tier 1 ──────────────────────────────────────────────────────────────────
  "attd|1|flutter|no|Shir0o/attd"
  "bible-read|1|flutter|yes|Shir0o/bible-read"
  "cisa-campus-work-tracker|1|node|yes|Shir0o/cisa-campus-work-tracker"
  "bnpb|1|flutter|no|Shir0o/bnpb"
  "auto-vol|1|flutter|no|Shir0o/auto-vol"
  "cleaning-tracker|1|flutter|no|Shir0o/cleaning-tracker"
  "diary|1|flutter|no|Shir0o/diary"
  "wave|1|flutter|no|Shir0o/wave"
  "road-song|1|flutter|no|Shir0o/road-song"
  "idle-flame|1|flutter|no|Shir0o/idle-flame"
  # ── Tier 2 ──────────────────────────────────────────────────────────────────
  "sleep-journal|2|flutter|no|Shir0o/sleep-journal"
  "idle|2|godot|no|Shir0o/idle"
  "csa|2|node|no|Shir0o/csa"
  "package-maker|2|node|no|Shir0o/package-builder"
  "notes|2|eleventy|no|Shir0o/notes"
  "inventory|2|node|no|Shir0o/inventory"
  "circle|2|flutter|no|Shir0o/circle"
  "shared-calendar|2|node|no|Shir0o/shared-calendar"
  "helpful-scripts|2|python|no|Shir0o/helpful-scripts"
)

# ─── Helpers ──────────────────────────────────────────────────────────────────

log()  { echo "  → $*"; }
info() { echo ""; echo "━━━ $* ━━━"; }
skip() { echo "  ⏭  $*"; }
warn() { echo "  ⚠  $*"; }

# Copy a file, creating parent dirs. In dry-run mode, just report.
install_file() {
  local src="$1" dst="$2"
  if $DRY_RUN; then
    if [[ -f "$dst" ]]; then
      if diff -q "$src" "$dst" > /dev/null 2>&1; then
        skip "$(basename "$dst") (already up to date)"
      else
        log "WOULD UPDATE $(basename "$dst")"
      fi
    else
      log "WOULD CREATE $(basename "$dst")"
    fi
  else
    mkdir -p "$(dirname "$dst")"
    cp "$src" "$dst"
    log "Installed $(basename "$dst")"
  fi
}

# ─── Agent doc migration ─────────────────────────────────────────────────────
# Merges content from GEMINI.md and CLAUDE.md into PROJECT.md, then deletes
# the originals. Deduplicates by stripping lines that match the shared base.

migrate_agent_docs() {
  local repo_dir="$1"
  local project_md="$repo_dir/PROJECT.md"
  local base_hash
  base_hash=$(md5 -q "$TEMPLATES/base-agents.md" 2>/dev/null || md5sum "$TEMPLATES/base-agents.md" | cut -d' ' -f1)

  # Collect content from old files (GEMINI.md, CLAUDE.md, .agents/AGENTS.md).
  # NOTE: We do NOT include "agents.md" because on case-insensitive macOS
  # filesystems it resolves to AGENTS.md, which we're about to overwrite.
  local old_files=()
  for f in "GEMINI.md" "CLAUDE.md" ".agents/AGENTS.md"; do
    [[ -f "$repo_dir/$f" ]] && old_files+=("$repo_dir/$f")
  done

  if [[ ${#old_files[@]} -eq 0 ]]; then
    return
  fi

  if $DRY_RUN; then
    for f in "${old_files[@]}"; do
      log "WOULD MIGRATE content from $(basename "$f") → PROJECT.md"
      log "WOULD DELETE $(basename "$f")"
    done
    return
  fi

  # If PROJECT.md doesn't exist yet, create it with a header
  if [[ ! -f "$project_md" ]]; then
    echo "# Project-Specific Rules" > "$project_md"
    echo "" >> "$project_md"
    echo "<!-- Repo-specific agent instructions. The rollout script never touches this file. -->" >> "$project_md"
    echo "" >> "$project_md"
  fi

  # Read each old file, strip lines that appear in the base template, append unique content
  local base_lines
  base_lines=$(cat "$TEMPLATES/base-agents.md")

  for f in "${old_files[@]}"; do
    local fname
    fname=$(basename "$f")
    echo "" >> "$project_md"
    echo "<!-- ── Migrated from $fname ── -->" >> "$project_md"
    echo "" >> "$project_md"

    # Strip common headers and sections that match the base template
    while IFS= read -r line; do
      # Skip lines that are exact matches to base template lines
      if echo "$base_lines" | grep -qxF "$line" 2>/dev/null; then
        continue
      fi
      # Skip duplicate top-level headers
      if [[ "$line" == "# AGENTS.md" ]] || [[ "$line" == "# CLAUDE.md" ]] || [[ "$line" == "# GEMINI.md" ]]; then
        continue
      fi
      # Skip the standard subtitle
      if [[ "$line" == *"Behavioral guidelines"* ]]; then
        continue
      fi
      echo "$line" >> "$project_md"
    done < "$f"

    log "Migrated content from $fname"
  done

  # Delete old files
  for f in "${old_files[@]}"; do
    rm "$f"
    log "Deleted $(basename "$f")"
  done

  # Clean up empty .agents/ directory if it exists
  [[ -d "$repo_dir/.agents" ]] && rmdir "$repo_dir/.agents" 2>/dev/null || true
}

# ─── Generate AGENTS.md from base + PROJECT.md ───────────────────────────────

generate_agents_md() {
  local repo_dir="$1"
  local agents_md="$repo_dir/AGENTS.md"
  local project_md="$repo_dir/PROJECT.md"

  if $DRY_RUN; then
    # Check for lowercase agents.md via git
    if (cd "$repo_dir" && git ls-files -- 'agents.md' 2>/dev/null | grep -q 'agents.md'); then
      log "WOULD RENAME agents.md → AGENTS.md (git mv)"
    fi
    if [[ -f "$project_md" ]]; then
      log "WOULD GENERATE AGENTS.md from base + PROJECT.md"
    else
      log "WOULD GENERATE AGENTS.md from base only (no PROJECT.md)"
    fi
    return
  fi

  # Handle lowercase agents.md → AGENTS.md rename via git
  if (cd "$repo_dir" && git ls-files -- 'agents.md' 2>/dev/null | grep -q 'agents.md'); then
    (cd "$repo_dir" && git mv agents.md AGENTS.md 2>/dev/null || true)
    log "Renamed agents.md → AGENTS.md"
  fi

  # Start with the base template
  cp "$TEMPLATES/base-agents.md" "$agents_md"

  # Append PROJECT.md if it exists
  if [[ -f "$project_md" ]]; then
    echo "" >> "$agents_md"
    echo "---" >> "$agents_md"
    echo "" >> "$agents_md"
    cat "$project_md" >> "$agents_md"
  fi

  log "Generated AGENTS.md"
}

# ─── Select the right dependabot template ─────────────────────────────────────

get_dependabot_template() {
  local framework="$1"
  case "$framework" in
    flutter) echo "$TEMPLATES/dependabot-flutter.yml" ;;
    node|eleventy) echo "$TEMPLATES/dependabot-node.yml" ;;
    python)  echo "$TEMPLATES/dependabot-python.yml" ;;
    godot)   echo "$TEMPLATES/dependabot-actions-only.yml" ;;
    *)       echo "$TEMPLATES/dependabot-actions-only.yml" ;;
  esac
}

# ─── Rename old CI workflow files to ci.yml ───────────────────────────────────

rename_ci_workflow() {
  local repo_dir="$1"
  local workflows_dir="$repo_dir/.github/workflows"

  [[ ! -d "$workflows_dir" ]] && return

  local old_names=("flutter_ci.yml" "flutter-tests.yml" "flutter.yml" "pr_build.yml")
  for old in "${old_names[@]}"; do
    if [[ -f "$workflows_dir/$old" ]]; then
      if $DRY_RUN; then
        log "WOULD RENAME $old → ci.yml"
      else
        mv "$workflows_dir/$old" "$workflows_dir/ci.yml"
        log "Renamed $old → ci.yml"
      fi
      return  # Only rename the first match
    fi
  done
}

# ─── Apply CI workflow template (only if no ci.yml exists after rename) ───────

apply_ci_template() {
  local repo_dir="$1" tier="$2" framework="$3"
  local workflows_dir="$repo_dir/.github/workflows"

  # Tier 2 repos: don't create CI if none exists, but rename if it does
  if [[ "$tier" == "2" ]] && [[ ! -d "$workflows_dir" ]]; then
    skip "No CI workflow (Tier 2, no existing workflows)"
    return
  fi

  # If ci.yml already exists (either original or renamed), don't overwrite
  # The script only standardizes the filename, not the content of existing CIs
  if [[ -f "$workflows_dir/ci.yml" ]]; then
    skip "ci.yml already exists"
    return
  fi

  # In dry-run mode, also account for old workflow files that would have been
  # renamed to ci.yml by rename_ci_workflow above
  if $DRY_RUN; then
    for old in "flutter_ci.yml" "flutter-tests.yml" "flutter.yml" "pr_build.yml"; do
      if [[ -f "$workflows_dir/$old" ]]; then
        skip "ci.yml (will exist after rename of $old)"
        return
      fi
    done
  fi

  # No CI at all — apply template for Tier 1
  if [[ "$tier" == "1" ]]; then
    case "$framework" in
      flutter) install_file "$TEMPLATES/ci-flutter.yml" "$workflows_dir/ci.yml" ;;
      node)    install_file "$TEMPLATES/ci-node.yml" "$workflows_dir/ci.yml" ;;
      *)       skip "No CI template for framework: $framework" ;;
    esac
  fi
}

# ─── Apply CodeQL ─────────────────────────────────────────────────────────────

apply_codeql() {
  local repo_dir="$1" framework="$2" has_functions="$3"
  local workflows_dir="$repo_dir/.github/workflows"

  # CodeQL for: node repos, or flutter repos with functions/
  if [[ "$framework" == "node" ]] || [[ "$framework" == "eleventy" ]] || [[ "$has_functions" == "yes" ]]; then
    install_file "$TEMPLATES/codeql.yml" "$workflows_dir/codeql.yml"
  else
    skip "CodeQL (pure $framework, no JS/TS)"
  fi
}

# ─── Apply branch ruleset ────────────────────────────────────────────────────

apply_ruleset() {
  local repo_dir="$1" tier="$2"
  local rulesets_dir="$repo_dir/.github/rulesets"

  local template
  if [[ "$tier" == "1" ]]; then
    template="$TEMPLATES/ruleset-tier1.json"
  else
    template="$TEMPLATES/ruleset-tier2.json"
  fi

  # Remove any old ruleset files with different names
  if [[ -d "$rulesets_dir" ]]; then
    for old in "$rulesets_dir"/*.json; do
      [[ ! -f "$old" ]] && continue
      if [[ "$(basename "$old")" != "main-branch-protection.json" ]]; then
        if $DRY_RUN; then
          log "WOULD RENAME $(basename "$old") → main-branch-protection.json"
        else
          rm "$old"
          log "Removed old ruleset $(basename "$old")"
        fi
      fi
    done
  fi

  install_file "$template" "$rulesets_dir/main-branch-protection.json"
}

# ─── Git operations ──────────────────────────────────────────────────────────

create_branch_and_pr() {
  local repo_dir="$1" github_repo="$2"

  if $DRY_RUN; then
    log "WOULD create branch '$BRANCH_NAME', commit, and open PR on $github_repo"
    return
  fi

  pushd "$repo_dir" > /dev/null

  local default_branch
  default_branch=$(git symbolic-ref refs/remotes/origin/HEAD 2>/dev/null | sed 's@^refs/remotes/origin/@@' || echo "main")

  # Stage ONLY the files the script manages — never git add -A
  local standard_files=(
    "AGENTS.md"
    "PROJECT.md"
    "SECURITY.md"
    ".github/CODEOWNERS"
    ".github/dependabot.yml"
    ".github/workflows/ci.yml"
    ".github/workflows/codeql.yml"
    ".github/rulesets/main-branch-protection.json"
  )
  for f in "${standard_files[@]}"; do
    [[ -f "$f" ]] && git add -f "$f"
  done

  # Also stage deletions of old files
  for f in "GEMINI.md" "CLAUDE.md" "agents.md" ".agents/AGENTS.md"; do
    git rm --cached "$f" 2>/dev/null || true
  done

  # Stage old CI workflow renames
  for old in "flutter_ci.yml" "flutter-tests.yml" "flutter.yml" "pr_build.yml"; do
    git rm --cached ".github/workflows/$old" 2>/dev/null || true
  done

  # Stage old ruleset renames
  git rm --cached ".github/rulesets/main-branch-ruleset.json" 2>/dev/null || true

  # Check if there are actually changes
  if git diff --cached --quiet; then
    skip "No changes to commit"
    git checkout "$default_branch" 2>/dev/null || true
    git branch -D "$BRANCH_NAME" 2>/dev/null || true
    popd > /dev/null
    return
  fi

  git commit --no-verify -m "$PR_TITLE"
  git push -u origin "$BRANCH_NAME" --force

  # Create PR (skip if one already exists)
  if gh pr view "$BRANCH_NAME" --repo "$github_repo" > /dev/null 2>&1; then
    log "PR already exists, updated branch"
  else
    gh pr create \
      --repo "$github_repo" \
      --title "$PR_TITLE" \
      --body "$PR_BODY" \
      --head "$BRANCH_NAME"
    log "Created PR on $github_repo"
  fi

  # Return to default branch
  git checkout "$default_branch" 2>/dev/null || true

  popd > /dev/null
}

# ─── Main loop ───────────────────────────────────────────────────────────────

main() {
  if $DRY_RUN; then
    echo ""
    echo "╔══════════════════════════════════════════════════════════════╗"
    echo "║  DRY RUN — no changes will be made. Use --apply to apply.  ║"
    echo "╚══════════════════════════════════════════════════════════════╝"
  else
    echo ""
    echo "╔══════════════════════════════════╗"
    echo "║  APPLYING STANDARDS TO REPOS     ║"
    echo "╚══════════════════════════════════╝"

    # Verify gh is authenticated
    if ! gh auth status > /dev/null 2>&1; then
      echo "ERROR: gh CLI is not authenticated. Run 'gh auth login' first."
      exit 1
    fi
  fi

  for entry in "${REPOS[@]}"; do
    IFS='|' read -r dir tier framework has_functions github_repo <<< "$entry"

    # Skip if filtering to a specific repo
    if [[ -n "$TARGET_REPO" ]] && [[ "$dir" != "$TARGET_REPO" ]]; then
      continue
    fi

    local repo_dir="$HOME_DIR/$dir"

    if [[ ! -d "$repo_dir" ]]; then
      warn "Directory not found: $repo_dir — skipping"
      continue
    fi

    info "$dir (Tier $tier, $framework)"

    # Switch to clean branch on default branch first
    if ! $DRY_RUN; then
      pushd "$repo_dir" > /dev/null
      local default_branch
      default_branch=$(git symbolic-ref refs/remotes/origin/HEAD 2>/dev/null | sed 's@^refs/remotes/origin/@@' || echo "main")
      git checkout -f "$default_branch" 2>/dev/null || git checkout -f main
      git pull --rebase origin "$default_branch" 2>/dev/null || true
      git branch -D "$BRANCH_NAME" 2>/dev/null || true
      git checkout -b "$BRANCH_NAME"
      popd > /dev/null
    fi

    # 1. Migrate old agent docs into PROJECT.md
    migrate_agent_docs "$repo_dir"

    # 2. Generate AGENTS.md from base + PROJECT.md
    generate_agents_md "$repo_dir"

    # 3. Apply CODEOWNERS
    install_file "$TEMPLATES/CODEOWNERS" "$repo_dir/.github/CODEOWNERS"

    # 4. Apply SECURITY.md
    install_file "$TEMPLATES/SECURITY.md" "$repo_dir/SECURITY.md"

    # 5. Apply dependabot
    local dep_template
    dep_template=$(get_dependabot_template "$framework")
    install_file "$dep_template" "$repo_dir/.github/dependabot.yml"

    # 6. Rename old CI workflows → ci.yml
    rename_ci_workflow "$repo_dir"

    # 7. Apply CI template if needed
    apply_ci_template "$repo_dir" "$tier" "$framework"

    # 8. Apply CodeQL
    apply_codeql "$repo_dir" "$framework" "$has_functions"

    # 9. Apply branch ruleset
    apply_ruleset "$repo_dir" "$tier"

    # 10. Create branch + commit + PR
    create_branch_and_pr "$repo_dir" "$github_repo"
  done

  echo ""
  if $DRY_RUN; then
    echo "✅ Dry run complete. Review the output above, then run with --apply."
  else
    echo "✅ All repos processed. Review and merge the PRs on GitHub."
  fi
}

main
